//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado_deduccion
    {
        public int id_empleado { get; set; }
        public Nullable<int> empleadoId { get; set; }
        public Nullable<int> deduccionId { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual tipo_deduccion tipo_deduccion { get; set; }
    }
}
