//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class puesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public puesto()
        {
            this.empleado = new HashSet<empleado>();
        }
    
        public int id_puesto { get; set; }
        public string nombre { get; set; }
        public string nive_riesgo_salario { get; set; }
        public Nullable<decimal> nivel_minimo_salario { get; set; }
        public Nullable<decimal> nivel_maximo_salario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empleado> empleado { get; set; }
    }
}
